// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace VoicevoxCoreSharp.Core.Native
{
    internal static unsafe partial class CoreUnsafe
    {
#if UNITY_IOS && !UNITY_EDITOR
        const string __DllName = "__Internal";
#else
        const string __DllName = "voicevox_core";
#endif
        



        /// <summary>
        ///  ONNX Runtimeの動的ライブラリの、バージョン付きのファイル名。
        ///
        ///  WindowsとAndroidでは ::voicevox_get_onnxruntime_lib_unversioned_filename と同じ。
        ///
        ///  \availability{
        ///    [リリース](https://github.com/voicevox/voicevox_core/releases)されているライブラリではiOSを除くプラットフォームで利用可能。詳細は&lt;a href="#voicevox-core-availability"&gt;ファイルレベルの"Availability"の節&lt;/a&gt;を参照。
        ///  }
        ///
        ///  \orig-impl{voicevox_get_onnxruntime_lib_versioned_filename}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_get_onnxruntime_lib_versioned_filename", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* voicevox_get_onnxruntime_lib_versioned_filename();

        /// <summary>
        ///  ONNX Runtimeの動的ライブラリの、バージョン無しのファイル名。
        ///
        ///  \availability{
        ///    [リリース](https://github.com/voicevox/voicevox_core/releases)されているライブラリではiOSを除くプラットフォームで利用可能。詳細は&lt;a href="#voicevox-core-availability"&gt;ファイルレベルの"Availability"の節&lt;/a&gt;を参照。
        ///  }
        ///
        ///  \orig-impl{voicevox_get_onnxruntime_lib_unversioned_filename}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_get_onnxruntime_lib_unversioned_filename", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* voicevox_get_onnxruntime_lib_unversioned_filename();

        /// <summary>
        ///  デフォルトの ::voicevox_onnxruntime_load_once のオプションを生成する。
        ///
        ///  @return デフォルトの ::voicevox_onnxruntime_load_once のオプション
        ///
        ///  \availability{
        ///    [リリース](https://github.com/voicevox/voicevox_core/releases)されているライブラリではiOSを除くプラットフォームで利用可能。詳細は&lt;a href="#voicevox-core-availability"&gt;ファイルレベルの"Availability"の節&lt;/a&gt;を参照。
        ///  }
        ///
        ///  \no-orig-impl{voicevox_make_default_load_onnxruntime_options}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_make_default_load_onnxruntime_options", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxLoadOnnxruntimeOptions voicevox_make_default_load_onnxruntime_options();

        /// <summary>
        ///  ::VoicevoxOnnxruntime のインスタンスが既に作られているならそれを得る。
        ///
        ///  作られていなければ`NULL`を返す。
        ///
        ///  @returns ::VoicevoxOnnxruntime のインスタンス
        ///
        ///  \orig-impl{voicevox_onnxruntime_get}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_onnxruntime_get", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxOnnxruntime* voicevox_onnxruntime_get();

        /// <summary>
        ///  ONNX Runtimeをロードして初期化する。
        ///
        ///  一度成功したら、以後は引数を無視して同じ参照を返す。
        ///
        ///  @param [in] options オプション
        ///  @param [out] out_onnxruntime ::VoicevoxOnnxruntime のインスタンス
        ///
        ///  @returns 結果コード
        ///
        ///  \availability{
        ///    [リリース](https://github.com/voicevox/voicevox_core/releases)されているライブラリではiOSを除くプラットフォームで利用可能。詳細は&lt;a href="#voicevox-core-availability"&gt;ファイルレベルの"Availability"の節&lt;/a&gt;を参照。
        ///  }
        ///
        ///  \safety{
        ///  - `options.filename`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  - `out_onnxruntime`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_onnxruntime_load_once}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_onnxruntime_load_once", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_onnxruntime_load_once(VoicevoxLoadOnnxruntimeOptions options, VoicevoxOnnxruntime** out_onnxruntime);

        /// <summary>
        ///  ONNX Runtimeを初期化する。
        ///
        ///  一度成功したら以後は同じ参照を返す。
        ///
        ///  @param [out] out_onnxruntime ::VoicevoxOnnxruntime のインスタンス
        ///
        ///  @returns 結果コード
        ///
        ///  \availability{
        ///    [リリース](https://github.com/voicevox/voicevox_core/releases)されているライブラリではiOSでのみ利用可能。詳細は&lt;a href="#voicevox-core-availability"&gt;ファイルレベルの"Availability"の節&lt;/a&gt;を参照。
        ///  }
        ///
        ///  \safety{
        ///  - `out_onnxruntime`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_onnxruntime_init_once}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_onnxruntime_init_once", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_onnxruntime_init_once(VoicevoxOnnxruntime** out_onnxruntime);

        /// <summary>
        ///  ::OpenJtalkRc を&lt;b&gt;構築&lt;/b&gt;(_construct_)する。
        ///
        ///  解放は ::voicevox_open_jtalk_rc_delete で行う。
        ///
        ///  @param [in] open_jtalk_dic_dir 辞書ディレクトリを指すUTF-8のパス
        ///  @param [out] out_open_jtalk 構築先
        ///
        ///  @returns 結果コード
        ///
        ///  \example{
        ///  ```c
        ///  OpenJtalkRc *open_jtalk;
        ///  voicevox_open_jtalk_rc_new("./open_jtalk_dic_utf_8-1.11", &amp;open_jtalk);
        ///  ```
        ///  }
        ///
        ///  \safety{
        ///  - `open_jtalk_dic_dir`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  - `out_open_jtalk`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_open_jtalk_rc_new}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_open_jtalk_rc_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_open_jtalk_rc_new(byte* open_jtalk_dic_dir, OpenJtalkRc** out_open_jtalk);

        /// <summary>
        ///  OpenJtalkの使うユーザー辞書を設定する。
        ///
        ///  この関数を呼び出した後にユーザー辞書を変更した場合、再度この関数を呼び出す必要がある。
        ///
        ///  @param [in] open_jtalk Open JTalkのオブジェクト
        ///  @param [in] user_dict ユーザー辞書
        ///
        ///  \orig-impl{voicevox_open_jtalk_rc_use_user_dict}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_open_jtalk_rc_use_user_dict", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_open_jtalk_rc_use_user_dict(OpenJtalkRc* open_jtalk, VoicevoxUserDict* user_dict);

        /// <summary>
        ///  日本語のテキストを解析する。
        ///
        ///  生成したJSON文字列を解放するには ::voicevox_json_free を使う。
        ///
        ///  @param [in] open_jtalk Open JTalkのオブジェクト
        ///  @param [in] text UTF-8の日本語テキスト
        ///  @param [out] output_accent_phrases_json 生成先
        ///
        ///  \orig-impl{voicevox_open_jtalk_rc_use_user_dict}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_open_jtalk_rc_analyze", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_open_jtalk_rc_analyze(OpenJtalkRc* open_jtalk, byte* text, byte** output_accent_phrases_json);

        /// <summary>
        ///  ::OpenJtalkRc を&lt;b&gt;破棄&lt;/b&gt;(_destruct_)する。
        ///
        ///  破棄対象への他スレッドでのアクセスが存在する場合、それらがすべて終わるのを待ってから破棄する。
        ///
        ///  この関数の呼び出し後に破棄し終えた対象にアクセスすると、プロセスを異常終了する。
        ///
        ///  @param [in] open_jtalk 破棄対象。nullable
        ///
        ///  \example{
        ///  ```c
        ///  voicevox_open_jtalk_rc_delete(open_jtalk);
        ///  ```
        ///  }
        ///
        ///  \no-orig-impl{voicevox_open_jtalk_rc_delete}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_open_jtalk_rc_delete", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void voicevox_open_jtalk_rc_delete(OpenJtalkRc* open_jtalk);

        /// <summary>
        ///  デフォルトの初期化オプションを生成する
        ///  @return デフォルト値が設定された初期化オプション
        ///
        ///  \no-orig-impl{voicevox_make_default_initialize_options}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_make_default_initialize_options", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxInitializeOptions voicevox_make_default_initialize_options();

        /// <summary>
        ///  voicevoxのバージョンを取得する。
        ///  @return SemVerでフォーマットされたバージョン。
        ///
        ///  \orig-impl{voicevox_get_version}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_get_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* voicevox_get_version();

        /// <summary>
        ///  AccentPhraseの配列からAudioQueryを作る。
        ///
        ///  生成したJSON文字列を解放するには ::voicevox_json_free を使う。
        ///
        ///  @param [in] accent_phrases_json AccentPhraseの配列のJSON文字列
        ///  @param [out] output_accent_phrases_json 生成先
        ///
        ///  \safety{
        ///  - `accent_phrases_json`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  - `output_audio_query_json`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_audio_query_create_from_accent_phrases}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_audio_query_create_from_accent_phrases", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_audio_query_create_from_accent_phrases(byte* accent_phrases_json, byte** output_audio_query_json);

        /// <summary>
        ///  与えられたJSONが`AudioQuery`型として不正であるときエラーを返す。
        ///
        ///  不正であるとは、以下のいずれかの条件を満たすことである。
        ///
        ///  - [Rust APIの`AudioQuery`型]としてデシリアライズ不可、もしくはJSONとして不正。
        ///  - `accent_phrases`の要素のうちいずれかが、 ::voicevox_accent_phrase_validate でエラーになる。
        ///  - `outputSamplingRate`が`24000`の倍数ではない、もしくは`0` (将来的に解消予定。cf. [#762])。
        ///
        ///  [Rust APIの`AudioQuery`型]: ../rust_api/voicevox_core/struct.AudioQuery.html
        ///  [#762]: https://github.com/VOICEVOX/voicevox_core/issues/762
        ///
        ///  次の状態に対しては警告のログを出す。将来的にはエラーになる予定。
        ///
        ///  - `accent_phrases`の要素のうちいずれかが警告が出る状態。
        ///  - `speedScale`が負。
        ///  - `volumeScale`が負。
        ///  - `prePhonemeLength`が負。
        ///  - `postPhonemeLength`が負。
        ///  - `outputSamplingRate`が`24000`以外の値（エラーと同様将来的に解消予定）。
        ///
        ///  @param [in] audio_query_json `AudioQuery`型のJSON
        ///
        ///  @returns 成功時には ::VOICEVOX_RESULT_OK 、失敗時には ::VOICEVOX_RESULT_INVALID_AUDIO_QUERY_ERROR
        ///
        ///  \safety{
        ///  - `audio_query_json`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_audio_query_validate}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_audio_query_validate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_audio_query_validate(byte* audio_query_json);

        /// <summary>
        ///  与えられたJSONが`AccentPhrase`型として不正であるときエラーを返す。
        ///
        ///  不正であるとは、以下のいずれかの条件を満たすことである。
        ///
        ///  - [Rust APIの`AccentPhrase`型]としてデシリアライズ不可、もしくはJSONとして不正。
        ///  - `moras`もしくは`pause_mora`の要素のうちいずれかが、 ::voicevox_mora_validate でエラーになる。
        ///  - `accent`が`0`。
        ///
        ///  [Rust APIの`AccentPhrase`型]: ../rust_api/voicevox_core/struct.AccentPhrase.html
        ///
        ///  次の状態に対しては警告のログを出す。将来的にはエラーになる予定。
        ///
        ///  - `moras`もしくは`pause_mora`の要素のうちいずれかが、警告が出る状態。
        ///  - `accent`が`moras`の数を超過している。
        ///
        ///  @param [in] accent_phrase_json `AccentPhrase`型のJSON
        ///
        ///  @returns 成功時には ::VOICEVOX_RESULT_OK 、失敗時には ::VOICEVOX_RESULT_INVALID_ACCENT_PHRASE_ERROR
        ///
        ///  \safety{
        ///  - `accent_phrase_json`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_accent_phrase_validate}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_accent_phrase_validate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_accent_phrase_validate(byte* accent_phrase_json);

        /// <summary>
        ///  与えられたJSONが`Mora`型として不正であるときエラーを返す。
        ///
        ///  不正であるとは、以下のいずれかの条件を満たすことである。
        ///
        ///  - [Rust APIの`Mora`型]としてデシリアライズ不可、もしくはJSONとして不正。
        ///  - `consonant`と`consonant_length`の有無が不一致。
        ///  - `consonant`が子音以外の音素であるか、もしくは音素として不正。
        ///  - `vowel`が子音であるか、もしくは音素として不正。
        ///
        ///  [Rust APIの`Mora`型]: ../rust_api/voicevox_core/struct.Mora.html
        ///
        ///  次の状態に対しては警告のログを出す。将来的にはエラーになる予定。
        ///
        ///  - `consonant_length`が負。
        ///  - `vowel_length`が負。
        ///
        ///  @param [in] mora_json `Mora`型のJSON
        ///
        ///  @returns 成功時には ::VOICEVOX_RESULT_OK 、失敗時には ::VOICEVOX_RESULT_INVALID_MORA_ERROR
        ///
        ///  \safety{
        ///  - `mora_json`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_mora_validate}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_mora_validate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_mora_validate(byte* mora_json);

        /// <summary>
        ///  与えられたJSONが`Score`型として不正であるときエラーを返す。
        ///
        ///  不正であるとは、以下のいずれかの条件を満たすことである。
        ///
        ///  - [Rust APIの`Score`型]としてデシリアライズ不可、もしくはJSONとして不正。
        ///  - `notes`の要素のうちいずれかが、 ::voicevox_note_validate でエラーになる。
        ///  - `notes`が空であるか、もしくは先頭が音符。
        ///
        ///  [Rust APIの`Score`型]: ../rust_api/voicevox_core/struct.Score.html
        ///
        ///  @param [in] score_json `Score`型のJSON
        ///
        ///  @returns 成功時には ::VOICEVOX_RESULT_OK 、失敗時には ::VOICEVOX_RESULT_INVALID_SCORE_ERROR
        ///
        ///  \safety{
        ///  - `score_json`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_score_validate}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_score_validate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_score_validate(byte* score_json);

        /// <summary>
        ///  与えられたJSONが`Note`型として不正であるときエラーを返す。
        ///
        ///  不正であるとは、以下のいずれかの条件を満たすことである。
        ///
        ///  - [Rust APIの`Note`型]としてデシリアライズ不可、もしくはJSONとして不正。
        ///  - `key`が`null`かつ`lyric`が`""`以外。
        ///  - `key`が非`null`かつ`lyric`が`""`。
        ///
        ///  [Rust APIの`Note`型]: ../rust_api/voicevox_core/struct.Note.html
        ///
        ///  @param [in] note_json `Note`型のJSON
        ///
        ///  @returns 成功時には ::VOICEVOX_RESULT_OK 、失敗時には ::VOICEVOX_RESULT_INVALID_NOTE_ERROR
        ///
        ///  \safety{
        ///  - `note_json`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_note_validate}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_note_validate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_note_validate(byte* note_json);

        /// <summary>
        ///  与えられたJSONが`FrameAudioQuery`型として不正であるときエラーを返す。
        ///
        ///  不正であるとは、以下の条件を満たすことである。
        ///
        ///  - [Rust APIの`FrameAudioQuery`型]としてデシリアライズ不可、もしくはJSONとして不正。
        ///
        ///  [Rust APIの`FrameAudioQuery`型]: ../rust_api/voicevox_core/struct.FrameAudioQuery.html
        ///
        ///  次の状態に対しては警告のログを出す。将来的にはエラーになる予定。
        ///
        ///  - `outputSamplingRate`が`24000`以外の値（将来的に解消予定）。
        ///
        ///  @param [in] frame_audio_query_json `FrameAudioQuery`型のJSON
        ///
        ///  @returns 成功時には ::VOICEVOX_RESULT_OK 、失敗時には ::VOICEVOX_RESULT_INVALID_FRAME_AUDIO_QUERY_ERROR
        ///
        ///  \safety{
        ///  - `frame_audio_query_json`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_frame_audio_query_validate}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_frame_audio_query_validate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_frame_audio_query_validate(byte* frame_audio_query_json);

        /// <summary>
        ///  与えられたJSONが`FramePhoneme`型として不正であるときエラーを返す。
        ///
        ///  不正であるとは、以下の条件を満たすことである。
        ///
        ///  - [Rust APIの`FramePhoneme`型]としてデシリアライズ不可、もしくはJSONとして不正。
        ///
        ///  [Rust APIの`FramePhoneme`型]: ../rust_api/voicevox_core/struct.FramePhoneme.html
        ///
        ///  @param [in] frame_phoneme_json `FramePhoneme`型のJSON
        ///
        ///  @returns 成功時には ::VOICEVOX_RESULT_OK 、失敗時には ::VOICEVOX_RESULT_INVALID_FRAME_PHONEME_ERROR
        ///
        ///  \safety{
        ///  - `frame_phoneme_json`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \no-orig-impl{voicevox_frame_phoneme_validate}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_frame_phoneme_validate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_frame_phoneme_validate(byte* frame_phoneme_json);

        /// <summary>
        ///  与えられた楽譜と歌唱合成用のクエリの組み合わせが、基本周波数と音量の生成に利用できるかどうかを確認する。
        ///
        ///  次のうちどれかを満たすならエラーを返す。
        ///
        ///  - `score_json`が ::voicevox_score_validate でエラーになる。
        ///  - `frame_audio_query_json`が ::voicevox_frame_audio_query_validate でエラーになる。
        ///  - `notes`が表す音素ID列と、`phonemes`が表す音素ID列が等しくない。ただし異なる音素の表現が同一のIDを表すことがある。
        ///
        ///  @param [in] score_json `Score`型のJSON
        ///  @param [in] frame_audio_query_json `FrameAudioQuery`型のJSON
        ///
        ///  @returns 成功時には ::VOICEVOX_RESULT_OK 、失敗時には ::VOICEVOX_RESULT_INVALID_SCORE_ERROR, ::VOICEVOX_RESULT_INVALID_FRAME_AUDIO_QUERY_ERROR, ::VOICEVOX_RESULT_INCOMPATIBLE_QUERIES_ERROR
        ///
        ///  \safety{
        ///  - `score_json`と`frame_audio_query_json`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///  \orig-impl{voicevox_ensure_compatible}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_ensure_compatible", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_ensure_compatible(byte* score_json, byte* frame_audio_query_json);

        /// <summary>
        ///  VVMファイルを開く。
        ///
        ///  @param [in] path vvmファイルへのUTF-8のファイルパス
        ///  @param [out] out_model 構築先
        ///
        ///  @returns 結果コード
        ///
        ///  \safety{
        ///  - `path`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  - `out_model`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_voice_model_file_open}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_voice_model_file_open", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_voice_model_file_open(byte* path, VoicevoxVoiceModelFile** out_model);

        /// <summary>
        ///  ::VoicevoxVoiceModelFile からIDを取得する。
        ///
        ///  @param [in] model 音声モデル
        ///  @param [out] output_voice_model_id 音声モデルID。詳細は ::VoicevoxVoiceModelId
        ///
        ///  \safety{
        ///  - `output_voice_model_id`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_voice_model_file_id}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_voice_model_file_id", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void voicevox_voice_model_file_id(VoicevoxVoiceModelFile* model, void/* byte[] */* output_voice_model_id);

        /// <summary>
        ///  ::VoicevoxVoiceModelFile からメタ情報を取得する。
        ///
        ///  JSONの解放は ::voicevox_json_free で行う。
        ///
        ///  @param [in] model 音声モデル
        ///
        ///  @returns メタ情報のJSON文字列
        ///
        ///  \orig-impl{voicevox_voice_model_file_create_metas_json}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_voice_model_file_create_metas_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* voicevox_voice_model_file_create_metas_json(VoicevoxVoiceModelFile* model);

        /// <summary>
        ///  ::VoicevoxVoiceModelFile を、所有しているファイルディスクリプタを閉じた上で&lt;b&gt;破棄&lt;/b&gt;(_destruct_)する。ファイルの削除(_delete_)&lt;b&gt;ではない&lt;/b&gt;。
        ///
        ///  破棄対象への他スレッドでのアクセスが存在する場合、それらがすべて終わるのを待ってから破棄する。
        ///
        ///  この関数の呼び出し後に破棄し終えた対象にアクセスすると、プロセスを異常終了する。
        ///
        ///  @param [in] model 破棄対象。nullable
        ///
        ///  \no-orig-impl{voicevox_voice_model_file_delete}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_voice_model_file_delete", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void voicevox_voice_model_file_delete(VoicevoxVoiceModelFile* model);

        /// <summary>
        ///  ::VoicevoxSynthesizer を&lt;b&gt;構築&lt;/b&gt;(_construct_)する。
        ///
        ///  @param [in] onnxruntime
        ///  @param [in] open_jtalk Open JTalkのオブジェクト
        ///  @param [in] options オプション
        ///  @param [out] out_synthesizer 構築先
        ///
        ///  @returns 結果コード
        ///
        ///  \safety{
        ///  - `onnxruntime`は ::voicevox_onnxruntime_load_once または ::voicevox_onnxruntime_init_once で得たものでなければならない。
        ///  - `out_synthesizer`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_synthesizer_new}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_synthesizer_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_synthesizer_new(VoicevoxOnnxruntime* onnxruntime, OpenJtalkRc* open_jtalk, VoicevoxInitializeOptions options, VoicevoxSynthesizer** out_synthesizer);

        /// <summary>
        ///  ::VoicevoxSynthesizer を&lt;b&gt;破棄&lt;/b&gt;(_destruct_)する。
        ///
        ///  破棄対象への他スレッドでのアクセスが存在する場合、それらがすべて終わるのを待ってから破棄する。
        ///
        ///  この関数の呼び出し後に破棄し終えた対象にアクセスすると、プロセスを異常終了する。
        ///
        ///  @param [in] synthesizer 破棄対象。nullable
        ///
        ///  \no-orig-impl{voicevox_synthesizer_delete}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_synthesizer_delete", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void voicevox_synthesizer_delete(VoicevoxSynthesizer* synthesizer);

        /// <summary>
        ///  音声モデルを読み込む。
        ///
        ///  @param [in] synthesizer 音声シンセサイザ
        ///  @param [in] model 音声モデル
        ///
        ///  @returns 結果コード
        ///
        ///  \orig-impl{voicevox_synthesizer_load_voice_model}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_synthesizer_load_voice_model", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_synthesizer_load_voice_model(VoicevoxSynthesizer* synthesizer, VoicevoxVoiceModelFile* model);

        /// <summary>
        ///  音声モデルの読み込みを解除する。
        ///
        ///  @param [in] synthesizer 音声シンセサイザ
        ///  @param [in] model_id 音声モデルID
        ///
        ///  @returns 結果コード
        ///
        ///  \safety{
        ///  - `model_id`は&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_synthesizer_unload_voice_model}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_synthesizer_unload_voice_model", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_synthesizer_unload_voice_model(VoicevoxSynthesizer* synthesizer, void/* byte[] */* model_id);

        /// <summary>
        ///  ::VoicevoxOnnxruntime のインスタンスを得る。
        ///
        ///  @param [in] synthesizer 音声シンセサイザ
        ///
        ///  @returns ::VoicevoxOnnxruntime のインスタンス
        ///
        ///  \orig-impl{voicevox_synthesizer_get_onnxruntime}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_synthesizer_get_onnxruntime", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxOnnxruntime* voicevox_synthesizer_get_onnxruntime(VoicevoxSynthesizer* synthesizer);

        /// <summary>
        ///  ハードウェアアクセラレーションがGPUモードか判定する。
        ///
        ///  @param [in] synthesizer 音声シンセサイザ
        ///
        ///  @returns GPUモードかどうか
        ///
        ///  \orig-impl{voicevox_synthesizer_is_gpu_mode}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_synthesizer_is_gpu_mode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool voicevox_synthesizer_is_gpu_mode(VoicevoxSynthesizer* synthesizer);

        /// <summary>
        ///  指定したIDの音声モデルが読み込まれているか判定する。
        ///
        ///  @param [in] synthesizer 音声シンセサイザ
        ///  @param [in] model_id 音声モデルID
        ///
        ///  @returns モデルが読み込まれているかどうか
        ///
        ///  \safety{
        ///  - `model_id`は&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_synthesizer_is_loaded_voice_model}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_synthesizer_is_loaded_voice_model", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool voicevox_synthesizer_is_loaded_voice_model(VoicevoxSynthesizer* synthesizer, void/* byte[] */* model_id);

        /// <summary>
        ///  今読み込んでいる音声モデルのメタ情報を、JSONで取得する。
        ///
        ///  JSONの解放は ::voicevox_json_free で行う。
        ///
        ///  @param [in] synthesizer 音声シンセサイザ
        ///
        ///  @return メタ情報のJSON文字列
        ///
        ///  \orig-impl{voicevox_synthesizer_create_metas_json}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_synthesizer_create_metas_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* voicevox_synthesizer_create_metas_json(VoicevoxSynthesizer* synthesizer);

        /// <summary>
        ///  ONNX Runtimeとして利用可能なデバイスの情報を、JSONで取得する。
        ///
        ///  JSONの解放は ::voicevox_json_free で行う。
        ///
        ///  あくまでONNX Runtimeが対応しているデバイスの情報であることに注意。GPUが使える環境ではなかったとしても`cuda`や`dml`は`true`を示しうる。
        ///
        ///  @param [in] onnxruntime
        ///  @param [out] output_supported_devices_json サポートデバイス情報のJSON文字列
        ///
        ///  @returns 結果コード
        ///
        ///  \example{
        ///  ```c
        ///  char *supported_devices;
        ///  VoicevoxResultCode result = voicevox_onnxruntime_create_supported_devices_json(onnxruntime, &amp;supported_devices);
        ///  ```
        ///  }
        ///
        ///  \safety{
        ///  - `onnxruntime`は ::voicevox_onnxruntime_load_once または ::voicevox_onnxruntime_init_once で得たものでなければならない。
        ///  - `output_supported_devices_json`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_onnxruntime_create_supported_devices_json}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_onnxruntime_create_supported_devices_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_onnxruntime_create_supported_devices_json(VoicevoxOnnxruntime* onnxruntime, byte** output_supported_devices_json);

        /// <summary>
        ///  AquesTalk風記法から、AudioQueryをJSONとして生成する。
        ///
        ///  生成したJSON文字列を解放するには ::voicevox_json_free を使う。
        ///
        ///  @param [in] synthesizer 音声シンセサイザ
        ///  @param [in] kana AquesTalk風記法
        ///  @param [in] style_id スタイルID
        ///  @param [out] output_audio_query_json 生成先
        ///
        ///  @returns 結果コード
        ///
        ///  \example{
        ///  ```c
        ///  char *audio_query;
        ///  voicevox_synthesizer_create_audio_query_from_kana(synthesizer, "コンニチワ'",
        ///                                                    2, // "四国めたん (ノーマル)"
        ///                                                    &amp;audio_query);
        ///  ```
        ///  }
        ///
        ///  \safety{
        ///  - `kana`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  - `output_audio_query_json`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_synthesizer_create_audio_query_from_kana}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_synthesizer_create_audio_query_from_kana", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_synthesizer_create_audio_query_from_kana(VoicevoxSynthesizer* synthesizer, byte* kana, uint style_id, byte** output_audio_query_json);

        /// <summary>
        ///  日本語テキストから、AudioQueryをJSONとして生成する。
        ///
        ///  生成したJSON文字列を解放するには ::voicevox_json_free を使う。
        ///
        ///  ::voicevox_synthesizer_create_accent_phrases と ::voicevox_audio_query_create_from_accent_phrases
        ///  が一体になったショートハンド。詳細は[テキスト音声合成の流れ]を参照。
        ///
        ///  @param [in] synthesizer 音声シンセサイザ
        ///  @param [in] text UTF-8の日本語テキスト
        ///  @param [in] style_id スタイルID
        ///  @param [out] output_audio_query_json 生成先
        ///
        ///  @returns 結果コード
        ///
        ///  \example{
        ///  ```c
        ///  char *audio_query;
        ///  voicevox_synthesizer_create_audio_query(synthesizer, "こんにちは",
        ///                                          2, // "四国めたん (ノーマル)"
        ///                                          &amp;audio_query);
        ///  ```
        ///  }
        ///
        ///  \safety{
        ///  - `text`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  - `output_audio_query_json`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_synthesizer_create_audio_query}
        ///
        ///  [テキスト音声合成の流れ]: https://github.com/VOICEVOX/voicevox_core/blob/main/docs/guide/user/tts-process.md
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_synthesizer_create_audio_query", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_synthesizer_create_audio_query(VoicevoxSynthesizer* synthesizer, byte* text, uint style_id, byte** output_audio_query_json);

        /// <summary>
        ///  AquesTalk風記法から、AccentPhrase (アクセント句)の配列をJSON形式で生成する。
        ///
        ///  生成したJSON文字列を解放するには ::voicevox_json_free を使う。
        ///
        ///  @param [in] synthesizer 音声シンセサイザ
        ///  @param [in] kana AquesTalk風記法
        ///  @param [in] style_id スタイルID
        ///  @param [out] output_accent_phrases_json 生成先
        ///
        ///  @returns 結果コード
        ///
        ///  \example{
        ///  ```c
        ///  char *accent_phrases;
        ///  voicevox_synthesizer_create_accent_phrases_from_kana(
        ///      synthesizer, "コンニチワ'",
        ///      2, // "四国めたん (ノーマル)"
        ///      &amp;accent_phrases);
        ///  ```
        ///  }
        ///
        ///  \safety{
        ///  - `kana`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  - `output_audio_query_json`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_synthesizer_create_accent_phrases_from_kana}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_synthesizer_create_accent_phrases_from_kana", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_synthesizer_create_accent_phrases_from_kana(VoicevoxSynthesizer* synthesizer, byte* kana, uint style_id, byte** output_accent_phrases_json);

        /// <summary>
        ///  日本語テキストから、AccentPhrase (アクセント句)の配列をJSON形式で生成する。
        ///
        ///  生成したJSON文字列を解放するには ::voicevox_json_free を使う。
        ///
        ///  ::voicevox_open_jtalk_rc_analyze と ::voicevox_synthesizer_replace_mora_data
        ///  が一体になったショートハンド。詳細は[テキスト音声合成の流れ]を参照。
        ///
        ///  @param [in] synthesizer 音声シンセサイザ
        ///  @param [in] text UTF-8の日本語テキスト
        ///  @param [in] style_id スタイルID
        ///  @param [out] output_accent_phrases_json 生成先
        ///
        ///  @returns 結果コード
        ///
        ///  \example{
        ///  ```c
        ///  char *accent_phrases;
        ///  voicevox_synthesizer_create_accent_phrases(synthesizer, "こんにちは",
        ///                                             2, // "四国めたん (ノーマル)"
        ///                                             &amp;accent_phrases);
        ///  ```
        ///  }
        ///
        ///  \safety{
        ///  - `text`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  - `output_audio_query_json`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_synthesizer_create_accent_phrases}
        ///
        ///  [テキスト音声合成の流れ]: https://github.com/VOICEVOX/voicevox_core/blob/main/docs/guide/user/tts-process.md
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_synthesizer_create_accent_phrases", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_synthesizer_create_accent_phrases(VoicevoxSynthesizer* synthesizer, byte* text, uint style_id, byte** output_accent_phrases_json);

        /// <summary>
        ///  AccentPhraseの配列の音高・音素長を、特定の声で生成しなおす。
        ///
        ///  生成したJSON文字列を解放するには ::voicevox_json_free を使う。
        ///
        ///  ::voicevox_synthesizer_replace_phoneme_length と ::voicevox_synthesizer_replace_mora_pitch
        ///  が一体になったショートハンド。詳細は[テキスト音声合成の流れ]を参照。
        ///
        ///  @param [in] synthesizer 音声シンセサイザ
        ///  @param [in] accent_phrases_json AccentPhraseの配列のJSON文字列
        ///  @param [in] style_id スタイルID
        ///  @param [out] output_accent_phrases_json 生成先
        ///
        ///  @returns 結果コード
        ///
        ///  \safety{
        ///  - `accent_phrases_json`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  - `output_audio_query_json`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_synthesizer_replace_mora_data}
        ///
        ///  [テキスト音声合成の流れ]: https://github.com/VOICEVOX/voicevox_core/blob/main/docs/guide/user/tts-process.md
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_synthesizer_replace_mora_data", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_synthesizer_replace_mora_data(VoicevoxSynthesizer* synthesizer, byte* accent_phrases_json, uint style_id, byte** output_accent_phrases_json);

        /// <summary>
        ///  AccentPhraseの配列の音素長を、特定の声で生成しなおす。
        ///
        ///  生成したJSON文字列を解放するには ::voicevox_json_free を使う。
        ///
        ///  @param [in] synthesizer 音声シンセサイザ
        ///  @param [in] accent_phrases_json AccentPhraseの配列のJSON文字列
        ///  @param [in] style_id スタイルID
        ///  @param [out] output_accent_phrases_json 生成先
        ///
        ///  @returns 結果コード
        ///
        ///  \safety{
        ///  - `accent_phrases_json`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  - `output_audio_query_json`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_synthesizer_replace_phoneme_length}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_synthesizer_replace_phoneme_length", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_synthesizer_replace_phoneme_length(VoicevoxSynthesizer* synthesizer, byte* accent_phrases_json, uint style_id, byte** output_accent_phrases_json);

        /// <summary>
        ///  AccentPhraseの配列の音高を、特定の声で生成しなおす。
        ///
        ///  生成したJSON文字列を解放するには ::voicevox_json_free を使う。
        ///
        ///  @param [in] synthesizer 音声シンセサイザ
        ///  @param [in] accent_phrases_json AccentPhraseの配列のJSON文字列
        ///  @param [in] style_id スタイルID
        ///  @param [out] output_accent_phrases_json 生成先
        ///
        ///  @returns 結果コード
        ///
        ///  \safety{
        ///  - `accent_phrases_json`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  - `output_audio_query_json`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_synthesizer_replace_mora_pitch}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_synthesizer_replace_mora_pitch", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_synthesizer_replace_mora_pitch(VoicevoxSynthesizer* synthesizer, byte* accent_phrases_json, uint style_id, byte** output_accent_phrases_json);

        /// <summary>
        ///  デフォルトの `voicevox_synthesizer_synthesis` のオプションを生成する
        ///  @return デフォルト値が設定された `voicevox_synthesizer_synthesis` のオプション
        ///
        ///  \no-orig-impl{voicevox_make_default_synthesis_options}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_make_default_synthesis_options", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxSynthesisOptions voicevox_make_default_synthesis_options();

        /// <summary>
        ///  AudioQueryから音声合成を行う。
        ///
        ///  生成したWAVデータを解放するには ::voicevox_wav_free を使う。
        ///
        ///  @param [in] synthesizer 音声シンセサイザ
        ///  @param [in] audio_query_json AudioQueryのJSON文字列
        ///  @param [in] style_id スタイルID
        ///  @param [in] options オプション
        ///  @param [out] output_wav_length 出力のバイト長
        ///  @param [out] output_wav 出力先
        ///
        ///  @returns 結果コード
        ///
        ///  \safety{
        ///  - `audio_query_json`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  - `output_wav_length`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  - `output_wav`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_synthesizer_synthesis}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_synthesizer_synthesis", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_synthesizer_synthesis(VoicevoxSynthesizer* synthesizer, byte* audio_query_json, uint style_id, VoicevoxSynthesisOptions options, nuint* output_wav_length, byte** output_wav);

        /// <summary>
        ///  デフォルトのテキスト音声合成オプションを生成する
        ///  @return テキスト音声合成オプション
        ///
        ///  \no-orig-impl{voicevox_make_default_tts_options}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_make_default_tts_options", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxTtsOptions voicevox_make_default_tts_options();

        /// <summary>
        ///  AquesTalk風記法から音声合成を行う。
        ///
        ///  生成したWAVデータを解放するには ::voicevox_wav_free を使う。
        ///
        ///  @param [in] synthesizer
        ///  @param [in] kana AquesTalk風記法
        ///  @param [in] style_id スタイルID
        ///  @param [in] options オプション
        ///  @param [out] output_wav_length 出力のバイト長
        ///  @param [out] output_wav 出力先
        ///
        ///  @returns 結果コード
        ///
        ///  \safety{
        ///  - `kana`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  - `output_wav_length`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  - `output_wav`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_synthesizer_tts_from_kana}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_synthesizer_tts_from_kana", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_synthesizer_tts_from_kana(VoicevoxSynthesizer* synthesizer, byte* kana, uint style_id, VoicevoxTtsOptions options, nuint* output_wav_length, byte** output_wav);

        /// <summary>
        ///  日本語テキストから音声合成を行う。
        ///
        ///  生成したWAVデータを解放するには ::voicevox_wav_free を使う。
        ///
        ///  ::voicevox_synthesizer_create_audio_query と ::voicevox_synthesizer_synthesis
        ///  が一体になったショートハンド。詳細は[テキスト音声合成の流れ]を参照。
        ///
        ///  @param [in] synthesizer
        ///  @param [in] text UTF-8の日本語テキスト
        ///  @param [in] style_id スタイルID
        ///  @param [in] options オプション
        ///  @param [out] output_wav_length 出力のバイト長
        ///  @param [out] output_wav 出力先
        ///
        ///  @returns 結果コード
        ///
        ///  \safety{
        ///  - `text`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  - `output_wav_length`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  - `output_wav`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_synthesizer_tts}
        ///
        ///  [テキスト音声合成の流れ]: https://github.com/VOICEVOX/voicevox_core/blob/main/docs/guide/user/tts-process.md
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_synthesizer_tts", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_synthesizer_tts(VoicevoxSynthesizer* synthesizer, byte* text, uint style_id, VoicevoxTtsOptions options, nuint* output_wav_length, byte** output_wav);

        /// <summary>
        ///  楽譜から歌唱音声合成用のクエリを作成する。
        ///
        ///  詳細はユーザーガイド[歌唱音声合成]を参照。
        ///
        ///  [歌唱音声合成]: https://github.com/VOICEVOX/voicevox_core/blob/main/docs/guide/user/song.md
        ///
        ///  生成したJSONを解放するには ::voicevox_json_free を使う。
        ///
        ///  @param [in] synthesizer 音声シンセサイザ
        ///  @param [in] score_json [`Score`型]を表すJSON
        ///  @param [in] style_id スタイルID
        ///  @param [out] output_frame_audio_query_json 生成先
        ///
        ///  [`Score`型]: ../rust_api/voicevox_core/struct.Score.html
        ///
        ///  @returns 結果コード
        ///
        ///  \example{
        ///  ```c
        ///  const char *kScore =
        ///      "{"
        ///      "  \"notes\": [ "
        ///      "    { \"key\": null, \"frame_length\": 15, \"lyric\": \"\" },"
        ///      "    { \"key\": 60, \"frame_length\": 45, \"lyric\": \"ド\" },"
        ///      "    { \"key\": 62, \"frame_length\": 45, \"lyric\": \"レ\" },"
        ///      "    { \"key\": 64, \"frame_length\": 45, \"lyric\": \"ミ\" },"
        ///      "    { \"key\": null, \"frame_length\": 15, \"lyric\": \"\" }"
        ///      "  ]"
        ///      "}";
        ///  const VoicevoxStyleId kSingingTeacher = 6000;
        ///
        ///  char *frame_audio_query;
        ///  const VoicevoxResultCode result =
        ///      voicevox_synthesizer_create_sing_frame_audio_query(
        ///          synthesizer, kScore, kSingingTeacher, &amp;frame_audio_query);
        ///  ```
        ///  }
        ///
        ///  \safety{
        ///  - `score_json`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  - `output_frame_audio_query_json`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_synthesizer_create_sing_frame_audio_query}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_synthesizer_create_sing_frame_audio_query", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_synthesizer_create_sing_frame_audio_query(VoicevoxSynthesizer* synthesizer, byte* score_json, uint style_id, byte** output_frame_audio_query_json);

        /// <summary>
        ///  楽譜と歌唱音声合成用のクエリから、フレームごとの基本周波数を生成する。
        ///
        ///  詳細はユーザーガイド[歌唱音声合成]を参照。
        ///
        ///  [歌唱音声合成]: https://github.com/VOICEVOX/voicevox_core/blob/main/docs/guide/user/song.md
        ///
        ///  生成したJSONを解放するには ::voicevox_json_free を使う。
        ///
        ///  @param [in] synthesizer 音声シンセサイザ
        ///  @param [in] score_json [`Score`型]を表すJSON
        ///  @param [in] frame_audio_query_json [`FrameAudioQuery`型]を表すJSON
        ///  @param [in] style_id スタイルID
        ///  @param [out] output_f0_json 生成先
        ///
        ///  [`Score`型]: ../rust_api/voicevox_core/struct.Score.html
        ///  [`FrameAudioQuery`型]: ../rust_api/voicevox_core/struct.FrameAudioQuery.html
        ///
        ///  @returns 結果コード
        ///
        ///  \safety{
        ///  - `score_json`と`frame_audio_query_json`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  - `output_f0_json`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_synthesizer_create_sing_frame_f0}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_synthesizer_create_sing_frame_f0", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_synthesizer_create_sing_frame_f0(VoicevoxSynthesizer* synthesizer, byte* score_json, byte* frame_audio_query_json, uint style_id, byte** output_f0_json);

        /// <summary>
        ///  楽譜と歌唱音声合成用のクエリから、フレームごとの音量を生成する。
        ///
        ///  詳細はユーザーガイド[歌唱音声合成]を参照。
        ///
        ///  [歌唱音声合成]: https://github.com/VOICEVOX/voicevox_core/blob/main/docs/guide/user/song.md
        ///
        ///  生成したJSONを解放するには ::voicevox_json_free を使う。
        ///
        ///  @param [in] synthesizer 音声シンセサイザ
        ///  @param [in] score_json [`Score`型]を表すJSON
        ///  @param [in] frame_audio_query_json [`FrameAudioQuery`型]を表すJSON
        ///  @param [in] style_id スタイルID
        ///  @param [out] output_volume_json 生成先
        ///
        ///  [`Score`型]: ../rust_api/voicevox_core/struct.Score.html
        ///  [`FrameAudioQuery`型]: ../rust_api/voicevox_core/struct.FrameAudioQuery.html
        ///
        ///  @returns 結果コード
        ///
        ///  \safety{
        ///  - `score_json`と`frame_audio_query_json`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  - `output_volume_json`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_synthesizer_create_sing_frame_volume}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_synthesizer_create_sing_frame_volume", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_synthesizer_create_sing_frame_volume(VoicevoxSynthesizer* synthesizer, byte* score_json, byte* frame_audio_query_json, uint style_id, byte** output_volume_json);

        /// <summary>
        ///  歌唱音声合成を行う。
        ///
        ///  詳細はユーザーガイド[歌唱音声合成]を参照。
        ///
        ///  [歌唱音声合成]: https://github.com/VOICEVOX/voicevox_core/blob/main/docs/guide/user/song.md
        ///
        ///  生成したWAVデータを解放するには ::voicevox_wav_free を使う。
        ///
        ///  @param [in] synthesizer 音声シンセサイザ
        ///  @param [in] frame_audio_query_json [`FrameAudioQuery`型]を表すJSON
        ///  @param [in] style_id スタイルID
        ///  @param [out] output_wav_length 出力のバイト長
        ///  @param [out] output_wav 出力先
        ///
        ///  [`FrameAudioQuery`型]: ../rust_api/voicevox_core/struct.FrameAudioQuery.html
        ///
        ///  @returns 結果コード
        ///
        ///  \example{
        ///  ```c
        ///  const VoicevoxStyleId kSinger = 3000;
        ///
        ///  uint8_t *wav;
        ///  size_t wav_length;
        ///  const VoicevoxResultCode result = voicevox_synthesizer_frame_synthesis(
        ///      synthesizer, frame_audio_query, kSinger, &amp;wav_length, &amp;wav);
        ///  ```
        ///  }
        ///
        ///  \safety{
        ///  - `frame_audio_query_json`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  - `output_wav_length`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  - `output_wav`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_synthesizer_frame_synthesis}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_synthesizer_frame_synthesis", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_synthesizer_frame_synthesis(VoicevoxSynthesizer* synthesizer, byte* frame_audio_query_json, uint style_id, nuint* output_wav_length, byte** output_wav);

        /// <summary>
        ///  JSON文字列を解放する。
        ///
        ///  @param [in] json 解放するJSON文字列。nullable
        ///
        ///  \safety{
        ///  - `json`がヌルポインタでないならば、以下のAPIで得られたポインタでなくてはいけない。
        ///      - ::voicevox_audio_query_create_from_accent_phrases
        ///      - ::voicevox_onnxruntime_create_supported_devices_json
        ///      - ::voicevox_voice_model_file_create_metas_json
        ///      - ::voicevox_open_jtalk_rc_analyze
        ///      - ::voicevox_synthesizer_create_metas_json
        ///      - ::voicevox_synthesizer_create_audio_query
        ///      - ::voicevox_synthesizer_create_audio_query_from_kana
        ///      - ::voicevox_synthesizer_create_accent_phrases
        ///      - ::voicevox_synthesizer_create_accent_phrases_from_kana
        ///      - ::voicevox_synthesizer_replace_mora_data
        ///      - ::voicevox_synthesizer_replace_phoneme_length
        ///      - ::voicevox_synthesizer_replace_mora_pitch
        ///      - ::voicevox_synthesizer_create_sing_frame_audio_query
        ///      - ::voicevox_synthesizer_create_sing_frame_f0
        ///      - ::voicevox_synthesizer_create_sing_frame_volume
        ///      - ::voicevox_user_dict_to_json
        ///  - 文字列の長さは生成時より変更されていてはならない。
        ///  - `json`がヌルポインタでないならば、&lt;a href="#voicevox-core-safety"&gt;読み込みと書き込みについて有効&lt;/a&gt;でなければならない。
        ///  - `json`がヌルポインタでないならば、以後&lt;b&gt;ダングリングポインタ&lt;/b&gt;(_dangling pointer_)として扱われなくてはならない。
        ///  }
        ///
        ///  \no-orig-impl{voicevox_json_free}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_json_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void voicevox_json_free(byte* json);

        /// <summary>
        ///  WAVデータを解放する。
        ///
        ///  @param [in] wav 解放するWAVデータ。nullable
        ///
        ///  \safety{
        ///  - `wav`がヌルポインタでないならば、以下のAPIで得られたポインタでなくてはいけない。
        ///      - ::voicevox_synthesizer_synthesis
        ///      - ::voicevox_synthesizer_tts
        ///      - ::voicevox_synthesizer_tts_from_kana
        ///      - ::voicevox_synthesizer_frame_synthesis
        ///  - `wav`がヌルポインタでないならば、&lt;a href="#voicevox-core-safety"&gt;読み込みと書き込みについて有効&lt;/a&gt;でなければならない。
        ///  - `wav`がヌルポインタでないならば、以後&lt;b&gt;ダングリングポインタ&lt;/b&gt;(_dangling pointer_)として扱われなくてはならない。
        ///  }
        ///
        ///  \no-orig-impl{voicevox_wav_free}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_wav_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void voicevox_wav_free(byte* wav);

        /// <summary>
        ///  結果コードに対応したメッセージ文字列を取得する。
        ///
        ///  @param [in] result_code 結果コード
        ///
        ///  @returns 結果コードに対応したメッセージ文字列
        ///
        ///  \examples{
        ///  ```c
        ///  const char *actual = voicevox_error_result_to_message(VOICEVOX_RESULT_OK);
        ///  const char *EXPECTED = "エラーが発生しませんでした";
        ///  assert(strcmp(actual, EXPECTED) == 0);
        ///  ```
        ///
        ///  ```c
        ///  const char *actual =
        ///      voicevox_error_result_to_message(VOICEVOX_RESULT_LOAD_MODEL_ERROR);
        ///  const char *EXPECTED = "modelデータ読み込みに失敗しました";
        ///  assert(strcmp(actual, EXPECTED) == 0);
        ///  ```
        ///  }
        ///
        ///  \no-orig-impl{voicevox_error_result_to_message}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_error_result_to_message", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* voicevox_error_result_to_message(VoicevoxResultCode result_code);

        /// <summary>
        ///  ::VoicevoxUserDictWord を最低限のパラメータで作成する。
        ///
        ///  @param [in] surface 表記
        ///  @param [in] pronunciation 読み
        ///  @param [in] accent_type アクセント型
        ///  @returns ::VoicevoxUserDictWord
        ///
        ///  \orig-impl{voicevox_user_dict_word_make}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_user_dict_word_make", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxUserDictWord voicevox_user_dict_word_make(byte* surface, byte* pronunciation, nuint accent_type);

        /// <summary>
        ///  ユーザー辞書をb&gt;構築&lt;/b&gt;(_construct_)する。
        ///
        ///  @returns ::VoicevoxUserDict
        ///
        ///  \orig-impl{voicevox_user_dict_new}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_user_dict_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxUserDict* voicevox_user_dict_new();

        /// <summary>
        ///  ユーザー辞書にファイルを読み込ませる。
        ///
        ///  @param [in] user_dict ユーザー辞書
        ///  @param [in] dict_path 読み込む辞書ファイルのパス
        ///  @returns 結果コード
        ///
        ///  \safety{
        ///  - `dict_path`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_user_dict_load}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_user_dict_load", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_user_dict_load(VoicevoxUserDict* user_dict, byte* dict_path);

        /// <summary>
        ///  ユーザー辞書に単語を追加する。
        ///
        ///  @param [in] ユーザー辞書
        ///  @param [in] word 追加する単語
        ///  @param [out] output_word_uuid 追加した単語のUUID
        ///  @returns 結果コード
        ///
        ///  # Safety
        ///  @param user_dict は有効な :VoicevoxUserDict のポインタであること
        ///
        ///  \safety{
        ///  - `word-&gt;surface`と`word-&gt;pronunciation`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  - `output_word_uuid`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_user_dict_add_word}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_user_dict_add_word", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_user_dict_add_word(VoicevoxUserDict* user_dict, VoicevoxUserDictWord* word, void/* byte[] */* output_word_uuid);

        /// <summary>
        ///  ユーザー辞書の単語を更新する。
        ///
        ///  @param [in] user_dict ユーザー辞書
        ///  @param [in] word_uuid 更新する単語のUUID
        ///  @param [in] word 新しい単語のデータ
        ///  @returns 結果コード
        ///
        ///  \safety{
        ///  - `word_uuid`は&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  - `word-&gt;surface`と`word-&gt;pronunciation`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_user_dict_update_word}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_user_dict_update_word", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_user_dict_update_word(VoicevoxUserDict* user_dict, void/* byte[] */* word_uuid, VoicevoxUserDictWord* word);

        /// <summary>
        ///  ユーザー辞書から単語を削除する。
        ///
        ///  @param [in] user_dict ユーザー辞書
        ///  @param [in] word_uuid 削除する単語のUUID
        ///  @returns 結果コード
        ///
        ///  \safety{
        ///  - `word_uuid`は&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_user_dict_remove_word}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_user_dict_remove_word", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_user_dict_remove_word(VoicevoxUserDict* user_dict, void/* byte[] */* word_uuid);

        /// <summary>
        ///  ユーザー辞書の単語をJSON形式で出力する。
        ///
        ///  生成したJSON文字列を解放するには ::voicevox_json_free を使う。
        ///
        ///  @param [in] user_dict ユーザー辞書
        ///  @param [out] output_json 出力先
        ///  @returns 結果コード
        ///
        ///  \safety{
        ///  - `output_json`は&lt;a href="#voicevox-core-safety"&gt;書き込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_user_dict_to_json}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_user_dict_to_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_user_dict_to_json(VoicevoxUserDict* user_dict, byte** output_json);

        /// <summary>
        ///  他のユーザー辞書をインポートする。
        ///
        ///  @param [in] user_dict ユーザー辞書
        ///  @param [in] other_dict インポートするユーザー辞書
        ///  @returns 結果コード
        ///
        ///  \orig-impl{voicevox_user_dict_import}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_user_dict_import", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_user_dict_import(VoicevoxUserDict* user_dict, VoicevoxUserDict* other_dict);

        /// <summary>
        ///  ユーザー辞書をファイルに保存する。
        ///
        ///  @param [in] user_dict ユーザー辞書
        ///  @param [in] path 保存先のファイルパス
        ///
        ///  \safety{
        ///  - `path`はヌル終端文字列を指し、かつ&lt;a href="#voicevox-core-safety"&gt;読み込みについて有効&lt;/a&gt;でなければならない。
        ///  }
        ///
        ///  \orig-impl{voicevox_user_dict_save}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_user_dict_save", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VoicevoxResultCode voicevox_user_dict_save(VoicevoxUserDict* user_dict, byte* path);

        /// <summary>
        ///  ユーザー辞書を&lt;b&gt;破棄&lt;/b&gt;(_destruct_)する。
        ///
        ///  破棄対象への他スレッドでのアクセスが存在する場合、それらがすべて終わるのを待ってから破棄する。
        ///
        ///  この関数の呼び出し後に破棄し終えた対象にアクセスすると、プロセスを異常終了する。
        ///
        ///  @param [in] user_dict 破棄対象。nullable
        ///
        ///  \no-orig-impl{voicevox_user_dict_delete}
        /// </summary>
        [DllImport(__DllName, EntryPoint = "voicevox_user_dict_delete", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void voicevox_user_dict_delete(VoicevoxUserDict* user_dict);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct VoicevoxLoadOnnxruntimeOptions
    {
        public byte* filename;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct VoicevoxOnnxruntime
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct OpenJtalkRc
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct VoicevoxInitializeOptions
    {
        public VoicevoxAccelerationMode acceleration_mode;
        public ushort cpu_num_threads;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct VoicevoxVoiceModelFile
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct VoicevoxSynthesizer
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct VoicevoxSynthesisOptions
    {
        [MarshalAs(UnmanagedType.U1)] public bool enable_interrogative_upspeak;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct VoicevoxTtsOptions
    {
        [MarshalAs(UnmanagedType.U1)] public bool enable_interrogative_upspeak;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct VoicevoxUserDict
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct VoicevoxUserDictWord
    {
        public byte* surface;
        public byte* pronunciation;
        public nuint accent_type;
        public VoicevoxUserDictWordType word_type;
        public uint priority;
    }


    internal enum VoicevoxResultCode : int
    {
        VOICEVOX_RESULT_OK = 0,
        VOICEVOX_RESULT_NOT_LOADED_OPENJTALK_DICT_ERROR = 1,
        VOICEVOX_RESULT_GET_SUPPORTED_DEVICES_ERROR = 3,
        VOICEVOX_RESULT_GPU_SUPPORT_ERROR = 4,
        VOICEVOX_RESULT_INIT_INFERENCE_RUNTIME_ERROR = 29,
        VOICEVOX_RESULT_STYLE_NOT_FOUND_ERROR = 6,
        VOICEVOX_RESULT_MODEL_NOT_FOUND_ERROR = 7,
        VOICEVOX_RESULT_RUN_MODEL_ERROR = 8,
        VOICEVOX_RESULT_ANALYZE_TEXT_ERROR = 11,
        VOICEVOX_RESULT_INVALID_UTF8_INPUT_ERROR = 12,
        VOICEVOX_RESULT_PARSE_KANA_ERROR = 13,
        VOICEVOX_RESULT_INVALID_AUDIO_QUERY_ERROR = 14,
        VOICEVOX_RESULT_INVALID_ACCENT_PHRASE_ERROR = 15,
        VOICEVOX_RESULT_OPEN_ZIP_FILE_ERROR = 16,
        VOICEVOX_RESULT_READ_ZIP_ENTRY_ERROR = 17,
        VOICEVOX_RESULT_INVALID_MODEL_HEADER_ERROR = 28,
        VOICEVOX_RESULT_MODEL_ALREADY_LOADED_ERROR = 18,
        VOICEVOX_RESULT_STYLE_ALREADY_LOADED_ERROR = 26,
        VOICEVOX_RESULT_INVALID_MODEL_DATA_ERROR = 27,
        VOICEVOX_RESULT_LOAD_USER_DICT_ERROR = 20,
        VOICEVOX_RESULT_SAVE_USER_DICT_ERROR = 21,
        VOICEVOX_RESULT_USER_DICT_WORD_NOT_FOUND_ERROR = 22,
        VOICEVOX_RESULT_USE_USER_DICT_ERROR = 23,
        VOICEVOX_RESULT_INVALID_USER_DICT_WORD_ERROR = 24,
        VOICEVOX_RESULT_INVALID_UUID_ERROR = 25,
        VOICEVOX_RESULT_INVALID_MORA_ERROR = 30,
        VOICEVOX_RESULT_INVALID_SCORE_ERROR = 31,
        VOICEVOX_RESULT_INVALID_NOTE_ERROR = 32,
        VOICEVOX_RESULT_INVALID_FRAME_AUDIO_QUERY_ERROR = 33,
        VOICEVOX_RESULT_INVALID_FRAME_PHONEME_ERROR = 34,
        VOICEVOX_RESULT_INCOMPATIBLE_QUERIES_ERROR = 35,
    }

    internal enum VoicevoxAccelerationMode : int
    {
        VOICEVOX_ACCELERATION_MODE_AUTO = 0,
        VOICEVOX_ACCELERATION_MODE_CPU = 1,
        VOICEVOX_ACCELERATION_MODE_GPU = 2,
    }

    internal enum VoicevoxUserDictWordType : int
    {
        VOICEVOX_USER_DICT_WORD_TYPE_PROPER_NOUN = 0,
        VOICEVOX_USER_DICT_WORD_TYPE_COMMON_NOUN = 1,
        VOICEVOX_USER_DICT_WORD_TYPE_VERB = 2,
        VOICEVOX_USER_DICT_WORD_TYPE_ADJECTIVE = 3,
        VOICEVOX_USER_DICT_WORD_TYPE_SUFFIX = 4,
    }


}
