<Project>
    <PropertyGroup>
        <!-- ref: binding/voicevox_core/crates/voicevox_core/onnxruntime-recommended-version.txt -->
        <VoicevoxOnnxRuntimeVersion>1.23.2</VoicevoxOnnxRuntimeVersion>
        <VoicevoxCoreCommitHash>9732b14a9589db3112453a40ab584b329c942a53</VoicevoxCoreCommitHash>
    </PropertyGroup>
</Project>
