<Project>
    <PropertyGroup>
        <!-- ref: binding/voicevox_core/crates/voicevox_core/onnxruntime-recommended-version.txt -->
        <VoicevoxOnnxRuntimeVersion>1.23.2</VoicevoxOnnxRuntimeVersion>
        <VoicevoxCoreCommitHash>74fdd4565a5bd867bd27c084908218e7bdb9d234</VoicevoxCoreCommitHash>
    </PropertyGroup>
</Project>
