name: Build dev Rust library
description: submoduleのVOICEVOX CORE Libraryをビルドする
inputs:
  cache-key:
    description: cache key
    required: true
  cache-path:
    description: cache path
    required: true

runs:
  using: composite
  steps:
    - uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      id: restore-dev-library
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ inputs.cache-key }}
    - if: ${{ steps.restore-dev-library.outputs.cache-hit != 'true' }}
      uses: actions-rust-lang/setup-rust-toolchain@ac90e63697ac2784f4ecfe2964e1a285c304003a # v1.14.1
      with:
        cache-workspaces: ./binding
    - if: ${{ steps.restore-dev-library.outputs.cache-hit != 'true' }}
      shell: bash
      working-directory: ./binding
      run: make build/dev-library
      env:
        VVCORE_BUILD_DOWNLOAD_AND_COPY_ORT: 1
    - if: ${{ steps.restore-dev-library.outputs.cache-hit != 'true' }}
      shell: bash
      working-directory: ./binding/voicevox_core/target/release
      # ライブラリのシンボリックリンクをコピーしてリンクを解除する
      run: |
        find . -type l | while read link; do
          target=$(readlink "$link")
          if [ -f "$target" ]; then
            cp "$target" "$link".tmp
            unlink "$link"
            mv "$link".tmp "$link"
          fi
        done
    - if: ${{ steps.restore-dev-library.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ inputs.cache-key }}
