on: 
  issue_comment:
    types: [created]

jobs:
  test_release:
    if: contains(github.event.comment.body, '/test_release')
    runs-on: ubuntu-latest
    steps:
      - id: get_tag
        run: echo tag="${BODY#/test_release }" >> $GITHUB_OUTPUT
        env:
          BODY: ${{ github.event.comment.body }}
      - id: download-voicevox_core
        uses: sevenc-nanashi/setup-voicevox@v0.1.0
        with:
          download-item: "core"
          path: voicevox_core_resources
          version: ${{ steps.get_tag.outputs.tag }}
      - run: cp ${{ steps.download-voicevox_core.outputs.entrypoint }} tests/VoicevoxCoreSharp.Core.Tests/resources/libvoicevox_core.so
      - run: mkdir -p tests/VoicevoxCoreSharp.Core.Tests/resources/model; cp -r ${{ steps.download-voicevox_core.outputs.entrypoint }}/../model/0.vvm tests/VoicevoxCoreSharp.Core.Tests/resources/model/sample.vvm
      - uses: actions/cache/restore@v3
        id: restore-open-jtalk-dictionary
        with:
          path: open_jtalk_dic_utf_8-1.11.tar.gz
          key: open_jtalk_dic_utf_8-1.11
      - if: ${{ steps.restore-open-jtalk-dictionary.outputs.cache-hit != 'true' }}
        run: curl -sSLfo open_jtalk_dic_utf_8-1.11.tar.gz https://jaist.dl.sourceforge.net/project/open-jtalk/Dictionary/open_jtalk_dic-1.11/open_jtalk_dic_utf_8-1.11.tar.gz
      - if: ${{ steps.restore-open-jtalk-dictionary.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v3
        with:
          path: open_jtalk_dic_utf_8-1.11.tar.gz
          key: open_jtalk_dic_utf_8-1.11
      - run: |
          cp open_jtalk_dic_utf_8-1.11.tar.gz ./tests/VoicevoxCoreSharp.Core.Tests/resources
          tar zxf ./tests/VoicevoxCoreSharp.Core.Tests/resources/open_jtalk_dic_utf_8-1.11.tar.gz -C tests/VoicevoxCoreSharp.Core.Tests/resources/
      - run: dotnet test
